show=drun
prompt=Applications
normal_window=true
style=/home/alfreditan/Documents/ArchSetup/wofi/style.css
location=center
width=55%
height=55%
xoffset=0
yoffset=0
orientation=vertical
columns=1
lines=10
allow_images=true
image_size=28
matching=fuzzy
insensitive=true
sort_order=alphabetical
gtk_dark=true
